#!/bin/bash

DESTINATIONDIR=$HOME
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
BACKUPDIR=$BASEDIR/backups/"$(date +%Y-%m-%d_%H-%M-%S)"

if [ -d "$BACKUPDIR" ]; then
	echo "Backup directory $BACKUPDIR already exists. Please wait literally one second and try again."
	exit
fi

# Loop through the files and folders listed in $BASEDIR/config
while IFS= read -r filepath
do
	# Remove trailing slash (not sure if this is necessary)
	filepath=${filepath%/}

	echo
	echo "Working on $filepath"

	oldfile=$DESTINATIONDIR/$filepath
	newfile=$BASEDIR/home-away-from-HOME/$filepath

	if [ ! -e $newfile ]; then
		echo "$newfile could not be found"
		continue
	fi

	# If the file is already correctly symlinked, skip.
	if [ "$(readlink $oldfile)" = "$newfile" ]; then
		echo "Symlink already exists for $oldfile"
		continue
	fi

	# If a file with this name already exists, copy it to the backup folder to avoid overwriting.
	if [ -e $oldfile ]; then
		echo "Copying existing $filepath to backup folder"
		mkdir -p $BACKUPDIR
		# Make a deep, recursive copy, removing symlinks.
		cp -RL $oldfile $BACKUPDIR
		rm -rf $oldfile
	fi

	echo "Creating symlink for $filepath"
	mkdir -p $(dirname $oldfile)
	ln -Ffs $newfile $oldfile
done < $BASEDIR/config
