#!/usr/bin/env bash
#
# fzf stub, for testing the interactive (`i`) branch of the y/N/i prompts.
#
# Real fzf echoes the selected INPUT lines back verbatim, and several scripts
# parse a prefix off the line they get (clean's array index, envsync's
# PAIR_IDX:KEY), so this stub selects from the candidates it was handed rather
# than emitting strings a test invented. A test that hardcoded output would
# pass while the real script broke.
#
# Candidates are saved so a test can assert what was *offered*, which is where
# the safety-relevant logic lives: that a protected branch is never listed,
# that a path outside the target is never listed.
#
# Requires $TEST_DIR, which every test file's setup() already exports.
#
#   stub_fzf_match PATTERN...  select every candidate containing a pattern
#   stub_fzf_line N...         select the Nth candidate, 1-based
#   stub_fzf_none              select nothing (empty output, exit 0)
#   stub_fzf_abort             user pressed ESC (exit 130)
#   no_fzf                     fzf genuinely absent from PATH
#   fzf_candidates             print what fzf was offered

_install_fzf_stub() {
    local mode="$1"
    shift

    mkdir -p "$TEST_DIR/bin"
    printf '%s\n' "$mode" > "$TEST_DIR/fzf-mode"
    : > "$TEST_DIR/fzf-args"
    [ "$#" -gt 0 ] && printf '%s\n' "$@" > "$TEST_DIR/fzf-args"

    cat > "$TEST_DIR/bin/fzf" <<'STUB'
#!/bin/sh
# Generated by tests/helpers/fzf.bash. Flags are ignored on purpose: the
# scripts pass display-only options (--with-nth, --delimiter, --header,
# --reverse) that do not change which lines come back out.
cat > "$TEST_DIR/fzf-candidates"
case "$(cat "$TEST_DIR/fzf-mode")" in
    abort) exit 130 ;;
    none)  exit 0 ;;
    match)
        while IFS= read -r pat; do
            [ -n "$pat" ] && grep -F -- "$pat" "$TEST_DIR/fzf-candidates"
        done < "$TEST_DIR/fzf-args"
        ;;
    line)
        while IFS= read -r n; do
            [ -n "$n" ] && sed -n "${n}p" "$TEST_DIR/fzf-candidates"
        done < "$TEST_DIR/fzf-args"
        ;;
esac
exit 0
STUB
    chmod +x "$TEST_DIR/bin/fzf"
    export PATH="$TEST_DIR/bin:$PATH"
}

stub_fzf_match() { _install_fzf_stub match "$@"; }
stub_fzf_line() { _install_fzf_stub line "$@"; }
stub_fzf_none() { _install_fzf_stub none; }
stub_fzf_abort() { _install_fzf_stub abort; }

# Mirror the whole PATH into one directory, minus fzf, and publish it as
# $NO_FZF_PATH. Dropping the PATH entries that contain fzf would be simpler but
# breaks wherever fzf shares a directory with git and friends, which is exactly
# the case on Alpine (/usr/bin/fzf), so absence has to be built rather than
# subtracted.
#
# Deliberately does NOT export PATH: replacing it for the whole bats process
# leaks into teardown and bats' own cleanup, which then cannot find `rm` once
# $TEST_DIR is gone. Apply it to just the command under test:
#
#   no_fzf
#   run env PATH="$NO_FZF_PATH" bash -c "echo 'i' | $TEST_DIR/clean ..."
no_fzf() {
    local dirs d f base
    mkdir -p "$TEST_DIR/no-fzf-bin"
    IFS=: read -ra dirs <<< "$PATH"
    for d in "${dirs[@]}"; do
        [ -d "$d" ] || continue
        for f in "$d"/*; do
            [ -e "$f" ] || continue
            base=${f##*/}
            [ "$base" = "fzf" ] && continue
            # First match wins, mirroring real PATH precedence
            [ -e "$TEST_DIR/no-fzf-bin/$base" ] || ln -s "$f" "$TEST_DIR/no-fzf-bin/$base" 2>/dev/null || true
        done
    done
    NO_FZF_PATH="$TEST_DIR/no-fzf-bin"
    export NO_FZF_PATH
}

fzf_candidates() { cat "$TEST_DIR/fzf-candidates"; }
